export type WarningLight = {
  id: string;
  name: string;
  description: string;
  severity: "info" | "warning" | "critical";
  image: string;
  urgency: string;
  fixInfo: string;
};

// Placeholder image for icons not present in /public
const PLACEHOLDER = "/warning-placeholder.png";

export const allWarningLights: WarningLight[] = [
  // --- Original warning lights (with icons/info) ---
  {
    id: "abs-light",
    name: "ABS Warning",
    description: "The Anti-lock Braking System (ABS) has detected a fault. This system prevents wheels from locking up during hard braking.",
    severity: "warning",
    image: "/ABS-light.png",
    urgency: "Have the ABS system inspected soon. You can continue driving, but avoid hard braking.",
    fixInfo: "Visit a mechanic to scan the ABS system for fault codes. The issue may be with sensors, wiring, or the ABS module.",
  },
  {
    id: "airbag-indicator",
    name: "Airbag Warning",
    description: "The airbag system has detected a fault. Airbags may not deploy properly in the event of a collision.",
    severity: "critical",
    image: "/airbag-indicator.png",
    urgency: "This requires immediate attention. Airbags are a critical safety feature and may not work if this light is on.",
    fixInfo: "Have a qualified technician run a diagnostic scan to identify the specific airbag system fault. Do not attempt to repair airbag systems yourself.",
  },
  {
    id: "battery-alert",
    name: "Battery Alert",
    description: "The battery or charging system is not functioning properly. This could indicate a failing battery, alternator, or electrical issue.",
    severity: "warning",
    image: "/battery-alert.png",
    urgency: "Drive to a service center immediately. Your vehicle could stall unexpectedly, especially at low speeds or when stopping.",
    fixInfo: "Check battery terminal connections for corrosion. Test the battery and alternator output. Replace components as needed.",
  },
  {
    id: "brake-warning",
    name: "Brake Warning",
    description: "A problem has been detected in the brake system. This could be low brake fluid, worn brake pads, or a hydraulic system failure.",
    severity: "critical",
    image: "/brake-warning.png",
    urgency: "Stop driving immediately. Brake system failures can result in complete loss of braking ability.",
    fixInfo: "Check brake fluid level in the master cylinder. If low, add fluid and check for leaks. If the light persists, call for a tow.",
  },
  {
    id: "check-engine-light",
    name: "Check Engine",
    description: "The engine control system has detected a fault. This could affect emissions, fuel economy, or engine performance.",
    severity: "warning",
    image: "/check-engine-light.png",
    urgency: "Schedule service soon unless the vehicle is driving abnormally. A flashing light indicates a more serious problem.",
    fixInfo: "Use an OBD-II code reader to identify the specific fault code, or visit a mechanic for professional diagnosis.",
  },
  {
    id: "engine-temperature",
    name: "Engine Temperature",
    description: "The engine coolant temperature is too high. This indicates the engine is overheating, which can cause severe damage.",
    severity: "critical",
    image: "/engine-temperature.png",
    urgency: "Pull over immediately and turn off the engine. Continuing to drive can cause catastrophic engine damage.",
    fixInfo: "Check coolant level in the radiator and overflow tank. Let the engine cool completely before opening the radiator cap.",
  },
  {
    id: "fog-lamp",
    name: "Fog Lamp Indicator",
    description: "The front fog lamps are currently illuminated. These provide additional lighting in foggy or low-visibility conditions.",
    severity: "info",
    image: "/fog-lamp.png",
    urgency: "No action required. This is an informational light showing the fog lamps are active.",
    fixInfo: "Turn off fog lamps when visibility improves to avoid blinding other drivers and conserve battery power.",
  },
  {
    id: "lane-departure",
    name: "Lane Departure Warning",
    description: "The vehicle is drifting out of its lane without a turn signal being activated. This system helps prevent unintended lane changes.",
    severity: "warning",
    image: "/lane-departure.png",
    urgency: "Pay attention to your driving position. The system is alerting you to stay in your lane.",
    fixInfo: "Stay alert and focused on the road. If the system seems overly sensitive, it may need recalibration by a technician.",
  },
  {
    id: "low-fuel",
    name: "Low Fuel",
    description: "The fuel level is low and approaching empty. You should refuel soon to avoid running out of gas.",
    severity: "info",
    image: "/low-fuel.png",
    urgency: "Refuel as soon as possible. Running out of fuel can damage the fuel pump and leave you stranded.",
    fixInfo: "Drive to the nearest gas station and fill up. Consider the distance to your destination when planning fuel stops.",
  },
  {
    id: "oil-pressure-light",
    name: "Oil Pressure",
    description: "Engine oil pressure is too low. This can cause severe engine damage if not addressed immediately.",
    severity: "critical",
    image: "/oil-pressure-light.png",
    urgency: "Stop the engine immediately. Low oil pressure can destroy the engine within minutes.",
    fixInfo: "Check engine oil level and add oil if low. If oil level is adequate, the oil pump or pressure sensor may be faulty.",
  },
  {
    id: "seat-belt",
    name: "Seat Belt Reminder",
    description: "One or more seat belts are not properly fastened. Seat belts are essential for occupant safety.",
    severity: "info",
    image: "/seat-belt.png",
    urgency: "Buckle all seat belts immediately. This light will continue to alert until all belts are secured.",
    fixInfo: "Ensure all passengers are properly buckled. Check that belts are not twisted and are securely latched.",
  },
  {
    id: "security-indicator",
    name: "Security Indicator",
    description: "The vehicle's security system is active or there may be an issue with the key or immobilizer system.",
    severity: "info",
    image: "/security-indicator.png",
    urgency: "This is usually informational. If the vehicle won't start, there may be a key or security system problem.",
    fixInfo: "Try using a different key if available. If problems persist, the security system may need to be reset by a dealer.",
  },
  {
    id: "shift-lock",
    name: "Shift Lock",
    description: "The transmission is locked in Park and requires the brake pedal to be pressed before shifting to another gear.",
    severity: "info",
    image: "/shift-lock.png",
    urgency: "Press the brake pedal firmly to unlock the transmission. This is a normal safety feature.",
    fixInfo: "If the transmission won't shift after pressing the brake, the brake light switch may be faulty and need replacement.",
  },
  {
    id: "tire-pressure-light",
    name: "Tire Pressure",
    description: "One or more tires have low air pressure. This affects handling, fuel economy, and tire life.",
    severity: "warning",
    image: "/tire-pressure-light.png",
    urgency: "Check and inflate tires soon. Driving on underinflated tires is dangerous and can cause blowouts.",
    fixInfo: "Use a tire pressure gauge to check all tires and inflate them to the recommended PSI shown on the tire placard.",
  },
  {
    id: "traction-control-malfunction",
    name: "Traction Control Malfunction",
    description: "The traction control system has detected a fault and may not function properly in slippery conditions.",
    severity: "warning",
    image: "/traction-control-malfunction.png",
    urgency: "Drive with extra caution, especially in wet or slippery conditions. Traction control helps prevent wheel spin.",
    fixInfo: "Have the traction control system diagnosed by a technician. The issue may be with sensors or the control module.",
  },
  {
    id: "traction-control",
    name: "Traction Control Active",
    description: "The traction control system is currently working to prevent wheel spin and maintain vehicle stability.",
    severity: "info",
    image: "/traction-control.png",
    urgency: "No action needed. The system is functioning normally and helping maintain traction.",
    fixInfo: "Continue driving normally. The system will automatically deactivate when no longer needed.",
  },
  {
    id: "transmission-temperature",
    name: "Transmission Temperature",
    description: "The transmission fluid temperature is too high. This can cause transmission damage if not addressed.",
    severity: "critical",
    image: "/transmission-temperature.png",
    urgency: "Stop driving to allow the transmission to cool. Continuing to drive can cause severe transmission damage.",
    fixInfo: "Pull over and let the engine idle to cool the transmission. Check transmission fluid level and condition.",
  },
  {
    id: "washer-fluid",
    name: "Low Washer Fluid",
    description: "The windshield washer fluid reservoir is low. This affects your ability to clean the windshield.",
    severity: "info",
    image: "/washer-fluid.png",
    urgency: "Refill washer fluid when convenient. This is not urgent but important for visibility.",
    fixInfo: "Add windshield washer fluid to the reservoir under the hood. Use appropriate washer fluid for your climate.",
  },
  // --- New/expanded warning lights (examples, add many more) ---
  {
    id: "ev-battery",
    name: "EV Battery Warning",
    description: "The high-voltage battery system in your electric or hybrid vehicle has detected a fault. This affects vehicle operation and safety.",
    severity: "critical",
    image: "/EVbattery-warning.png",
    urgency: "Stop driving and contact your dealer immediately. High-voltage systems can be dangerous if not handled properly.",
    fixInfo: "Do not attempt to service high-voltage battery systems yourself. Contact a qualified electric vehicle technician.",
  },
  {
    id: "lane-keep-assist",
    name: "Lane Keep Assist Warning",
    description: "The lane keep assist system has malfunctioned and may not help keep the vehicle in its lane automatically.",
    severity: "warning",
    image: "/lane-keep.png",
    urgency: "Drive with extra caution. The system may not provide lane-keeping assistance until repaired.",
    fixInfo: "Have the lane keep assist system checked by a qualified technician. The issue may require sensor calibration.",
  },
  // Add many more entries here...
  // --- Additional warning lights from user-provided list ---
  {
    id: "reduced-power-warning",
    name: "Reduced Power Warning",
    description: "The engine or transmission has entered reduced power mode due to a detected fault. Performance is limited to protect the vehicle.",
    severity: "warning",
    image: "/reduced-power.png",
    urgency: "Drive with caution. The vehicle has limited power and may not accelerate normally. Service soon.",
    fixInfo: "Have the vehicle diagnosed for engine or transmission faults. The reduced power mode is a protective feature.",
  },
  {
    id: "press-clutch-pedal",
    name: "Press Clutch Pedal",
    description: "The clutch pedal must be pressed to start the engine or shift gears in a manual transmission vehicle.",
    severity: "info",
    image: "/clutch-pedal.png",
    urgency: "Press the clutch pedal to proceed. This is a normal safety feature for manual transmissions.",
    fixInfo: "If the light stays on after pressing the clutch, the clutch switch may be faulty and need replacement.",
  },
  {
    id: "press-brake-pedal",
    name: "Press Brake Pedal",
    description: "The brake pedal must be pressed to start the engine or shift from Park in an automatic transmission vehicle.",
    severity: "info",
    image: "/brake-pedal.png",
    urgency: "Press the brake pedal to proceed. This is a normal safety feature for automatic transmissions.",
    fixInfo: "If the light stays on after pressing the brake, the brake switch may be faulty and need replacement.",
  },
  {
    id: "powertrain-fault",
    name: "Powertrain Fault",
    description: "A fault has been detected in the powertrain system, which includes the engine, transmission, and related components.",
    severity: "warning",
    image: "/powertrain-fault.png",
    urgency: "Service the vehicle as soon as possible. Performance, fuel economy, or drivability may be affected.",
    fixInfo: "Have the powertrain system diagnosed by a professional. The issue may be with engine, transmission, or sensors.",
  },
  {
    id: "power-steering-warning",
    name: "Power Steering Warning Light",
    description: "The power steering system has detected a fault. Steering may become much harder, especially at low speeds.",
    severity: "warning",
    image: "/power-steering.png",
    urgency: "Steering will be more difficult, especially when parking or turning. Service the system soon.",
    fixInfo: "Check power steering fluid level and add if low. If fluid is adequate, have the system inspected by a technician.",
  },
  {
    id: "steering-wheel-lock",
    name: "Steering Wheel Lock",
    description: "The steering wheel is locked in position, typically when the key is removed or the ignition is off.",
    severity: "info",
    image: "/steering-wheel-lock.png",
    urgency: "Unlock the steering wheel before attempting to drive. This is a normal anti-theft feature.",
    fixInfo: "Insert the key and turn it while gently turning the steering wheel to unlock. If stuck, consult your owner's manual.",
  },
  {
    id: "parking-brake-light",
    name: "Parking Brake Light",
    description: "The parking brake is engaged or there is a fault in the parking brake system that needs attention.",
    severity: "warning",
    image: "/parking-brake.png",
    urgency: "Release the parking brake before driving. If the light remains on, there may be a system fault.",
    fixInfo: "Ensure the parking brake is fully released. If the light stays on, have the parking brake system checked.",
  },
  {
    id: "trailer-tow-hitch-warning",
    name: "Trailer Tow Hitch Warning",
    description: "There is an issue with the trailer tow hitch connection or the trailer's electrical system.",
    severity: "warning",
    image: "/trailer-tow-hitch.png",
    urgency: "Check the trailer connection before driving. Faulty connections can cause accidents.",
    fixInfo: "Ensure the hitch is properly secured and all electrical connections are clean and properly connected.",
  },
  {
    id: "service-vehicle-soon",
    name: "Service Vehicle Soon",
    description: "A general fault has been detected in one of the vehicle's systems. Professional diagnosis is recommended.",
    severity: "warning",
    image: "/service-vehicle-soon.png",
    urgency: "Schedule service at your earliest convenience. The vehicle may continue to operate normally.",
    fixInfo: "Have the vehicle scanned for diagnostic codes to identify the specific system that needs attention.",
  },
  {
    id: "overdrive-light",
    name: "Overdrive Light",
    description: "The overdrive function is turned off or there is a fault in the overdrive system. This affects fuel economy.",
    severity: "info",
    image: "/overdrive-light.png",
    urgency: "Drive with caution. Fuel economy may be reduced with overdrive off.",
    fixInfo: "Turn overdrive on if needed for better fuel economy. If the light is flashing, have the system checked.",
  },
  {
    id: "oil-change-reminder",
    name: "Oil Change Reminder",
    description: "It's time for an oil change based on mileage or time intervals. Regular oil changes are essential for engine health.",
    severity: "info",
    image: "/oil-change-reminder.png",
    urgency: "Schedule an oil change soon to maintain engine performance and longevity.",
    fixInfo: "Change the engine oil and filter according to your vehicle's maintenance schedule, then reset the reminder.",
  },
  {
    id: "master-warning-light",
    name: "Master Warning Light",
    description: "A general warning has been activated for one or more vehicle systems. Check the information display for details.",
    severity: "warning",
    image: "/master-warning.png",
    urgency: "Check the vehicle's information display or instrument cluster for specific warning messages.",
    fixInfo: "Address the specific warning shown in the display. This light indicates there are other warnings to review.",
  },
  {
    id: "icy-road-warning",
    name: "Icy Road Warning Light",
    description: "Road conditions may be icy based on temperature sensors. This helps alert drivers to potentially slippery conditions.",
    severity: "info",
    image: "/icy-road.png",
    urgency: "Reduce speed and drive carefully. Be prepared for slippery road conditions.",
    fixInfo: "Be alert for icy patches, especially on bridges and overpasses. Maintain safe following distance.",
  },
  {
    id: "gas-cap",
    name: "Gas/Fuel Cap",
    description: "The fuel cap is loose, missing, or not properly sealed. This can cause emissions issues and trigger the check engine light.",
    severity: "warning",
    image: "/gas-cap.png",
    urgency: "Tighten or replace the fuel cap to prevent fuel vapor leaks and emissions problems.",
    fixInfo: "Check that the fuel cap is properly tightened. If damaged or missing, replace it with an approved cap.",
  },
  {
    id: "distance-warning",
    name: "Distance Warning",
    description: "You are following the vehicle ahead too closely. The system may alert you or automatically apply brakes.",
    severity: "info",
    image: "/distance-warning.png",
    urgency: "Increase your following distance to maintain safe driving conditions.",
    fixInfo: "Maintain a safe distance from other vehicles. The recommended distance increases with speed.",
  },
  {
    id: "catalytic-converter-warning",
    name: "Catalytic Converter Warning",
    description: "There is a problem with the catalytic converter or emissions system. This affects emissions and may impact performance.",
    severity: "warning",
    image: "/catalytic-converter.png",
    urgency: "Service the emissions system soon to avoid potential damage and ensure proper vehicle operation.",
    fixInfo: "Have the emissions system checked by a mechanic. The catalytic converter may need replacement if damaged.",
  },
  {
    id: "brake-pad-warning",
    name: "Brake Pad Warning",
    description: "The brake pads are worn and need replacement soon. Worn brake pads reduce braking effectiveness and can damage rotors.",
    severity: "warning",
    image: "/brake-pad.png",
    urgency: "Replace brake pads soon to maintain safe braking performance and prevent rotor damage.",
    fixInfo: "Have brake pads inspected and replaced by a qualified technician. Consider replacing rotors if they're worn.",
  },
  {
    id: "brake-lights-warning",
    name: "Brake Lights Warning",
    description: "One or more brake lights are not working properly. This affects your visibility to other drivers.",
    severity: "info",
    image: "/brake-lights.png",
    urgency: "Replace faulty brake light bulbs for safety. Other drivers need to see when you're braking.",
    fixInfo: "Check and replace any burned-out brake light bulbs. Ensure all brake lights are working properly.",
  },
  {
    id: "automatic-gearbox-warning",
    name: "Automatic Gearbox Warning",
    description: "There is a problem with the automatic transmission system. This can affect shifting and vehicle operation.",
    severity: "warning",
    image: "/automatic-gearbox.png",
    urgency: "Service the transmission soon. Shifting may be affected and could lead to transmission damage.",
    fixInfo: "Have the transmission checked by a professional. The issue may be with fluid, sensors, or internal components.",
  },
  {
    id: "awd-indicator",
    name: "All Wheel Drive (AWD/4WD)",
    description: "The all-wheel drive or four-wheel drive system is active or there is a fault in the system.",
    severity: "info",
    image: "/awd-indicator.png",
    urgency: "If flashing or indicating a fault, service the AWD/4WD system soon.",
    fixInfo: "Check your owner's manual for specific AWD/4WD system information or have it checked by a technician.",
  },
  {
    id: "4wd-lock-indicator",
    name: "4 Wheel Drive (4WD) LOCK Indicator Light",
    description: "Four-wheel drive lock mode is engaged or there is a fault in the 4WD system.",
    severity: "info",
    image: "/4wd-lock.png",
    urgency: "If not intended, disengage the lock mode. Service the system if a fault is indicated.",
    fixInfo: "Switch off lock mode if not needed for current driving conditions. Have the system checked if faulty.",
  },
  {
    id: "air-suspension",
    name: "Air Suspension",
    description: "There is a problem with the air suspension system. This affects ride quality and vehicle height adjustment.",
    severity: "warning",
    image: "/air-suspension.png",
    urgency: "Ride quality may be affected. Service the air suspension system soon.",
    fixInfo: "Have the air suspension system inspected. The issue may be with air bags, compressors, or sensors.",
  },
  {
    id: "lamp-out",
    name: "Lamp Out",
    description: "One or more exterior lights are not working properly. This affects your visibility and other drivers' ability to see you.",
    severity: "info",
    image: "/lamp-out.png",
    urgency: "Replace faulty bulbs for safety. Proper lighting is essential for safe driving.",
    fixInfo: "Check and replace any burned-out exterior light bulbs. Ensure all lights are working properly.",
  },
  {
    id: "auto-high-beam",
    name: "Auto High Beam",
    description: "The automatic high beam system is active or there is a fault in the system.",
    severity: "info",
    image: "/auto-high-beam.png",
    urgency: "If not working as expected, service the automatic high beam system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "headlight-range-control",
    name: "Headlight Range Control",
    description: "The headlight range adjustment system is active or there is a fault in the system.",
    severity: "info",
    image: "/headlight-range-control.png",
    urgency: "If not working as expected, service the headlight range control system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "adaptive-light-system",
    name: "Adaptive Light System",
    description: "The adaptive headlight system is active or there is a fault in the system.",
    severity: "info",
    image: "/adaptive-light-system.png",
    urgency: "If not working as expected, service the adaptive light system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "side-light-indicator",
    name: "Side Light Indicator",
    description: "The side lights (parking lights) are currently illuminated.",
    severity: "info",
    image: "/sidelight-indicator.png",
    urgency: "No action needed unless the lights are not intended to be on.",
    fixInfo: "Turn off side lights if they are not needed for current driving conditions.",
  },
  {
    id: "rear-fog-lights-on",
    name: "Rear Fog Lights Switched On",
    description: "The rear fog lights are currently illuminated to improve visibility in foggy conditions.",
    severity: "info",
    image: "/rear-fog-lights.png",
    urgency: "No action needed unless the lights are not intended to be on.",
    fixInfo: "Turn off rear fog lights when visibility improves to avoid blinding following drivers.",
  },
  {
    id: "rain-light-sensor",
    name: "Rain and Light Sensor",
    description: "The automatic rain or light sensor system is active or there is a fault in the system.",
    severity: "info",
    image: "/rain-light-sensor.png",
    urgency: "If not working as expected, service the rain and light sensor system.",
    fixInfo: "Check the sensor for dirt or damage, or have the system checked by a technician.",
  },
  {
    id: "windshield-defrost",
    name: "Windshield Defrost / Rear Window Defrost",
    description: "The windshield or rear window defrost system is active or there is a fault in the system.",
    severity: "info",
    image: "/windshield-defrost.png",
    urgency: "No action needed unless the defrost system is not working properly.",
    fixInfo: "Check the defrost system if windows are not clearing properly. May need sensor or system repair.",
  },
  {
    id: "key-not-in-vehicle",
    name: "Key Not in Vehicle",
    description: "The key fob is not detected inside the vehicle. This prevents starting the engine.",
    severity: "warning",
    image: "/key-not-in-vehicle.png",
    urgency: "Do not attempt to drive without the key. Retrieve the key fob before starting the vehicle.",
    fixInfo: "Bring the key fob into the vehicle. If the key is inside but not detected, the battery may be low.",
  },
  {
    id: "hood-open",
    name: "Hood/Bonnet Open",
    description: "The hood or bonnet is open or not properly latched. This can be dangerous while driving.",
    severity: "warning",
    image: "/hood-open.png",
    urgency: "Stop and close the hood securely before driving. An open hood can obstruct vision and cause accidents.",
    fixInfo: "Check that the hood is properly latched and the safety catch is engaged.",
  },
  {
    id: "hazard-lights-on",
    name: "Hazard Lights On",
    description: "The hazard warning lights are currently flashing to indicate the vehicle is stopped or in an emergency situation.",
    severity: "info",
    image: "/hood-open.png",
    urgency: "No action needed unless the hazard lights are not intended to be on.",
    fixInfo: "Turn off hazard lights when they are no longer needed for safety or emergency purposes.",
  },
  {
    id: "door-ajar",
    name: "Door Ajar",
    description: "One or more doors are open or not properly latched. This can be dangerous while driving.",
    severity: "warning",
    image: "/door-ajar.png",
    urgency: "Stop and close all doors securely before driving. Open doors can cause accidents and injuries.",
    fixInfo: "Check that all doors are properly closed and latched. Ensure the door ajar light goes out.",
  },
  {
    id: "recirculated-cabin-air",
    name: "Recirculated Cabin Air",
    description: "The cabin air is being recirculated instead of drawing in fresh outside air.",
    severity: "info",
    image: "/recirculated-cabin-air.png",
    urgency: "No action needed unless fresh air is desired instead of recirculated air.",
    fixInfo: "Turn off recirculation mode if you want fresh outside air to enter the cabin.",
  },
  {
    id: "rear-spoiler-warning",
    name: "Rear Spoiler Warning",
    description: "There is a problem with the rear spoiler system. The spoiler may not deploy or retract properly.",
    severity: "warning",
    image: "/rear-spoiler.png",
    urgency: "Have the spoiler system checked soon to ensure proper operation.",
    fixInfo: "Service the rear spoiler system. The issue may be with motors, sensors, or control systems.",
  },
  {
    id: "park-assist-pilot",
    name: "Parking with Park Assist Pilot",
    description: "The park assist system is active or there is a fault in the system.",
    severity: "info",
    image: "/park-assist-pilot.png",
    urgency: "If not working as expected, service the park assist system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "key-fob-battery-low",
    name: "Key Fob Battery Low",
    description: "The key fob battery is low and needs replacement soon. This may affect remote functions.",
    severity: "warning",
    image: "/key-fob-battery-low.png",
    urgency: "Replace the key fob battery soon to avoid being unable to unlock or start the vehicle.",
    fixInfo: "Replace the key fob battery with the correct type. Refer to your owner's manual for battery specifications.",
  },
  {
    id: "ignition-switch-warning",
    name: "Ignition Switch Warning",
    description: "There is a problem with the ignition switch or ignition system. This may affect starting the vehicle.",
    severity: "warning",
    image: "/ignition-switch.png",
    urgency: "Service the ignition system soon to prevent starting problems.",
    fixInfo: "Have the ignition system checked by a technician. The issue may be with the switch or related components.",
  },
  {
    id: "hill-descent-control",
    name: "Hill Descent Control",
    description: "The hill descent control system is active or there is a fault in the system.",
    severity: "info",
    image: "/hill-descent-control.png",
    urgency: "If not working as expected, service the hill descent control system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "forward-collision-warning",
    name: "Forward Collision Warning",
    description: "The system has detected a potential collision ahead and is warning you to take action.",
    severity: "critical",
    image: "/forward-collision-warning.png",
    urgency: "Brake or steer immediately to avoid the collision. The system may also apply automatic braking.",
    fixInfo: "Stay alert and maintain a safe following distance. The system is designed to help prevent accidents.",
  },
  {
    id: "eco-driving-indicator",
    name: "Eco Driving Indicator",
    description: "Eco mode is active, optimizing the vehicle for fuel-efficient driving by adjusting various systems.",
    severity: "info",
    image: "/eco-driving.png",
    urgency: "No action needed unless you want to disable eco mode for different driving characteristics.",
    fixInfo: "Turn off eco mode if you prefer normal driving characteristics or need maximum performance.",
  },
  {
    id: "cruise-control",
    name: "Cruise Control",
    description: "The cruise control system is active and maintaining a set speed automatically.",
    severity: "info",
    image: "/cruise-control.png",
    urgency: "No action needed unless you want to disable cruise control.",
    fixInfo: "Turn off cruise control if you need to manually control your speed or in heavy traffic.",
  },
  {
    id: "adaptive-cruise-control",
    name: "Adaptive Cruise Control",
    description: "The adaptive cruise control system is active or there is a fault in the system.",
    severity: "info",
    image: "/adaptive-cruise-control.png",
    urgency: "If not working as expected, service the adaptive cruise control system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "convertible-roof-warning",
    name: "Convertible Roof Warning Light",
    description: "There is a problem with the convertible roof system. The roof may not operate properly.",
    severity: "warning",
    image: "/convertible-roof-warning.png",
    urgency: "Service the roof system soon to ensure proper operation.",
    fixInfo: "Have the convertible roof system checked by a qualified technician.",
  },
  {
    id: "brake-hold-indicator",
    name: "Brake Hold Indicator Light",
    description: "The brake hold system is active or there is a fault in the system.",
    severity: "info",
    image: "/brake-hold.png",
    urgency: "If not working as expected, service the brake hold system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "blind-spot-indicator",
    name: "Blind Spot Indicator Light",
    description: "The blind spot monitoring system is active or there is a fault in the system.",
    severity: "info",
    image: "/blind-spot.png",
    urgency: "If not working as expected, service the blind spot monitoring system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "auto-windscreen-wiping",
    name: "Auto Windscreen Wiping",
    description: "The automatic wiper system is active or there is a fault in the system.",
    severity: "info",
    image: "/auto-windscreen-wiping.png",
    urgency: "If not working as expected, service the automatic wiper system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "automatic-emergency-braking",
    name: "Automatic Emergency Braking (AEB)",
    description: "The automatic emergency braking system is active or there is a fault in the collision prevention system.",
    severity: "critical",
    image: "/automatic-emergency-braking.png",
    urgency: "If not working as expected, service the automatic emergency braking system immediately.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a qualified technician.",
  },
  {
    id: "winter-mode",
    name: "Winter Mode",
    description: "Winter driving mode is active, optimizing the vehicle for cold weather and slippery road conditions.",
    severity: "info",
    image: "/winter-mode.png",
    urgency: "No action needed unless you want to disable winter mode for different driving characteristics.",
    fixInfo: "Turn off winter mode if you prefer normal driving characteristics or are driving in warm conditions.",
  },
  {
    id: "frost-warning",
    name: "Frost Warning Light",
    description: "Road conditions may be icy or frosty based on temperature sensors. This helps alert drivers to potentially slippery conditions.",
    severity: "warning",
    image: "/frost-warning.png",
    urgency: "Reduce speed and drive carefully on potentially icy roads. Be prepared for slippery conditions.",
    fixInfo: "Be alert for slippery conditions and maintain safe following distance. Frost can form even at temperatures above freezing.",
  },
  {
    id: "start-stop-warning",
    name: "Start/Stop Warning Light",
    description: "There is a problem with the automatic start/stop system. The engine may not automatically restart when needed.",
    severity: "warning",
    image: "/start-stop.png",
    urgency: "Service the start/stop system soon to ensure proper operation and fuel savings.",
    fixInfo: "Have the automatic start/stop system checked by a professional technician.",
  },
  {
    id: "speed-limiter",
    name: "Speed Limiter",
    description: "The speed limiter system is active or there is a fault in the system.",
    severity: "info",
    image: "/speed-limiter.png",
    urgency: "If not working as expected, service the speed limiter system.",
    fixInfo: "Check your owner's manual for system operation or have it checked by a technician.",
  },
  {
    id: "ev-mode",
    name: "EV Mode",
    description: "Electric vehicle mode is active, allowing the vehicle to operate on electric power only when possible.",
    severity: "info",
    image: "/ev-mode.png",
    urgency: "No action needed unless you want to disable EV mode for different driving characteristics.",
    fixInfo: "Turn off EV mode if you prefer hybrid operation or need maximum power output.",
  },
]; 