export type WarningLight = {
  id: string;
  name: string;
  description: string;
  severity: "info" | "warning" | "critical";
  image: string;
  urgency: string;
  fixInfo: string;
  videoUrl?: string;
};

// Placeholder image for icons not present in /public
const PLACEHOLDER = "/warning-placeholder.png";

export const allWarningLights: WarningLight[] = [
  // --- Original warning lights (with icons/info) ---
  {
    id: "abs-light",
    name: "ABS Warning",
    description: "There’s an issue with the Anti-lock Braking System (ABS). Get it inspected soon.",
    severity: "warning",
    image: "/ABS-light.png",
    urgency: "Get it inspected soon, but you can continue driving carefully.",
    fixInfo: "Have a mechanic scan the ABS system. Avoid hard braking.",
    videoUrl: "https://www.youtube.com/watch?v=KT1ax3JuoPo"
  },
  {
    id: "airbag-indicator",
    name: "Airbag Warning",
    description: "There may be an issue with the airbag system. Get it checked immediately.",
    severity: "critical",
    image: "/airbag-indicator.png",
    urgency: "Needs immediate attention. Airbags may not deploy in a crash.",
    fixInfo: "Have a technician run a diagnostic to check airbag sensors and modules.",
    videoUrl: "https://www.youtube.com/watch?v=2olDNq6RYkA"
  },
  {
    id: "battery-alert",
    name: "Battery Alert",
    description: "There may be a problem with your battery or charging system.",
    severity: "warning",
    image: "/battery-alert.png",
    urgency: "Drive to a shop immediately. Your car could stall soon.",
    fixInfo: "Check battery connections and alternator output.",
    videoUrl: "https://www.youtube.com/watch?v=rIgZrF8vW3I"
  },
  {
    id: "brake-warning",
    name: "Brake Warning",
    description: "There’s a brake system problem. Stop the vehicle safely and check.",
    severity: "critical",
    image: "/brake-warning.png",
    urgency: "Stop driving immediately. Brakes could be failing.",
    fixInfo: "Check brake fluid level. Call a tow if the light remains.",
    videoUrl: "https://www.youtube.com/watch?v=Qta5_Kz9f60"
  },
  {
    id: "check-engine-light",
    name: "Check Engine",
    description: "A potential issue with the engine or emissions system. Diagnosis recommended.",
    severity: "warning",
    image: "/check-engine-light.png",
    urgency: "Schedule service soon unless the car drives abnormally.",
    fixInfo: "Use a code reader or visit a mechanic for diagnostics.",
    videoUrl: "https://www.youtube.com/watch?v=2P8N1cKYNhM"
  },
  {
    id: "engine-temperature",
    name: "Engine Temperature",
    description: "The engine is overheating. Stop the vehicle immediately and allow it to cool.",
    severity: "critical",
    image: "/engine-temperature.png",
    urgency: "Pull over immediately to avoid severe engine damage.",
    fixInfo: "Check coolant level. Let engine cool before opening radiator.",
    videoUrl: "https://www.youtube.com/watch?v=WlN50Z5D6JI"
  },
  {
    id: "fog-lamp",
    name: "Fog Lamp Indicator",
    description: "Your front fog lamps are active.",
    severity: "info",
    image: "/fog-lamp.png",
    urgency: "No action needed. This is an informational light.",
    fixInfo: "Turn off fog lights if visibility is clear.",
    videoUrl: "https://www.youtube.com/watch?v=VeGcUCeMO_A"
  },
  {
    id: "lane-departure",
    name: "Lane Departure Warning",
    description: "The car is drifting out of lane without signaling.",
    severity: "warning",
    image: "/lane-departure.png",
    urgency: "Pay attention. System detects unintended lane changes.",
    fixInfo: "Stay alert or recalibrate lane assist system if faulty.",
    videoUrl: "https://www.youtube.com/watch?v=k0n2EeHeTwI"
  },
  {
    id: "low-fuel",
    name: "Low Fuel",
    description: "Fuel is low. You should refuel soon.",
    severity: "info",
    image: "/low-fuel.png",
    urgency: "Fill up your tank as soon as possible.",
    fixInfo: "Drive to the nearest gas station.",
    videoUrl: "https://www.youtube.com/watch?v=DCbyVR4n0zg"
  },
  {
    id: "oil-pressure-light",
    name: "Oil Pressure",
    description: "Low oil pressure. Stop immediately and check the oil level.",
    severity: "critical",
    image: "/oil-pressure-light.png",
    urgency: "Stop driving immediately. Engine damage is likely.",
    fixInfo: "Check oil level. Add oil or call a tow if it persists.",
    videoUrl: "https://www.youtube.com/watch?v=RUu9gLgG8fs"
  },
  {
    id: "seat-belt",
    name: "Seat Belt Reminder",
    description: "A seat belt is unbuckled.",
    severity: "info",
    image: "/seat-belt.png",
    urgency: "Buckle seatbelt immediately.",
    fixInfo: "Ensure all passengers are buckled.",
    videoUrl: "https://www.youtube.com/watch?v=X2UeFJTFxK0"
  },
  {
    id: "security-indicator",
    name: "Security Indicator",
    description: "Car security system is active or there may be an issue with the key.",
    severity: "info",
    image: "/security-indicator.png",
    urgency: "Informational unless the car won’t start.",
    fixInfo: "Try another key or reset the security system.",
    videoUrl: "https://www.youtube.com/watch?v=pbr0uIffYBM"
  },
  {
    id: "shift-lock",
    name: "Shift Lock",
    description: "The brake pedal must be pressed to shift out of Park.",
    severity: "info",
    image: "/shift-lock.png",
    urgency: "Press brake before shifting. No issue if functioning normally.",
    fixInfo: "Check brake light switch if car doesn’t shift.",
    videoUrl: "https://www.youtube.com/watch?v=lUEWzWkk5D8"
  },
  {
    id: "tire-pressure-light",
    name: "Tire Pressure",
    description: "One or more tires may be underinflated.",
    severity: "warning",
    image: "/tire-pressure-light.png",
    urgency: "Check tire pressures soon. Driving on low tires is dangerous.",
    fixInfo: "Inflate tires to the recommended PSI.",
    videoUrl: "https://www.youtube.com/watch?v=gB6k0K9vYd8"
  },
  {
    id: "traction-control-malfunction",
    name: "Traction Control Malfunction",
    description: "There is a malfunction in the traction control system.",
    severity: "warning",
    image: "/traction-control-malfunction.png",
    urgency: "Caution when driving. Reduced traction in poor conditions.",
    fixInfo: "Get the traction control system inspected.",
    videoUrl: "https://www.youtube.com/watch?v=2FZtSEnQf4M"
  },
  {
    id: "traction-control",
    name: "Traction Control Active",
    description: "The traction control system is currently active.",
    severity: "info",
    image: "/traction-control.png",
    urgency: "Informational. System is preventing wheel spin.",
    fixInfo: "Drive normally. No action required.",
    videoUrl: "https://www.youtube.com/watch?v=9MFU5vECoZc"
  },
  {
    id: "transmission-temperature",
    name: "Transmission Temperature",
    description: "Transmission fluid is too hot. Pull over and allow it to cool.",
    severity: "critical",
    image: "/transmission-temperature.png",
    urgency: "Stop driving to cool transmission. Severe damage risk.",
    fixInfo: "Pull over, idle car. Let it cool before continuing.",
    videoUrl: "https://www.youtube.com/watch?v=gcLZd-cj5mQ"
  },
  {
    id: "washer-fluid",
    name: "Low Washer Fluid",
    description: "Windshield washer fluid is low. Refill when convenient.",
    severity: "info",
    image: "/washer-fluid.png",
    urgency: "Not urgent. Refill at your convenience.",
    fixInfo: "Add washer fluid to reservoir under the hood.",
    videoUrl: "https://www.youtube.com/watch?v=HbOBbEjgK70"
  },
  // --- New/expanded warning lights (examples, add many more) ---
  {
    id: "ev-battery",
    name: "EV Battery Warning",
    description: "There is a problem with the high-voltage battery in your electric or hybrid vehicle.",
    severity: "critical",
    image: PLACEHOLDER,
    urgency: "Stop driving and contact your dealer or service center immediately.",
    fixInfo: "Do not attempt to service high-voltage systems yourself.",
  },
  {
    id: "lane-keep-assist",
    name: "Lane Keep Assist Warning",
    description: "There is a malfunction in the lane keep assist system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "System may not keep you in lane. Drive with caution.",
    fixInfo: "Have the system checked by a qualified technician.",
  },
  {
    id: "air-brake-warning",
    name: "Air Brake Warning",
    description: "Air pressure in the brake system is too low (common in trucks/buses).",
    severity: "critical",
    image: PLACEHOLDER,
    urgency: "Stop immediately. Brakes may fail.",
    fixInfo: "Check for air leaks and call for service.",
  },
  {
    id: "side-stand-warning",
    name: "Side Stand Warning",
    description: "The side stand is down or not fully retracted.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Do not ride with the side stand down.",
    fixInfo: "Retract the side stand before riding.",
  },
  // Add many more entries here...
  // --- Additional warning lights from user-provided list ---
  {
    id: "reduced-power-warning",
    name: "Reduced Power Warning",
    description: "The engine or transmission is in reduced power mode due to a detected fault.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Drive with caution. Performance is limited. Service soon.",
    fixInfo: "Have the vehicle diagnosed for engine or transmission faults.",
  },
  {
    id: "press-clutch-pedal",
    name: "Press Clutch Pedal",
    description: "Press the clutch pedal to start the engine or shift gears (manual transmission).",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Press clutch to proceed. No issue if functioning normally.",
    fixInfo: "If the light stays on, check the clutch switch or consult a mechanic.",
  },
  {
    id: "press-brake-pedal",
    name: "Press Brake Pedal",
    description: "Press the brake pedal to start the engine or shift from Park (automatic transmission).",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Press brake to proceed. No issue if functioning normally.",
    fixInfo: "If the light stays on, check the brake switch or consult a mechanic.",
  },
  {
    id: "powertrain-fault",
    name: "Powertrain Fault",
    description: "A fault has been detected in the powertrain (engine, transmission, or related systems).",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Service as soon as possible. Performance may be affected.",
    fixInfo: "Have the vehicle diagnosed for powertrain issues.",
  },
  {
    id: "power-steering-warning",
    name: "Power Steering Warning Light",
    description: "There is a problem with the power steering system. Steering may be difficult.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Steering may be harder. Service soon.",
    fixInfo: "Check power steering fluid or have the system inspected.",
  },
  {
    id: "steering-wheel-lock",
    name: "Steering Wheel Lock",
    description: "The steering wheel is locked. Usually requires key or button to unlock.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Unlock before driving. If stuck, consult manual or mechanic.",
    fixInfo: "Try turning the wheel while turning the key/button. If it won't unlock, seek help.",
  },
  {
    id: "parking-brake-light",
    name: "Parking Brake Light",
    description: "The parking brake is engaged or there is a fault in the parking brake system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Release parking brake before driving. If it stays on, check for faults.",
    fixInfo: "Ensure brake is fully released. If light remains, have system checked.",
  },
  {
    id: "trailer-tow-hitch-warning",
    name: "Trailer Tow Hitch Warning",
    description: "There is an issue with the trailer tow hitch or its connection.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Check trailer connection before driving.",
    fixInfo: "Ensure hitch is secure and electrical connections are correct.",
  },
  {
    id: "service-vehicle-soon",
    name: "Service Vehicle Soon",
    description: "A general fault has been detected. Service is required soon.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Schedule service at your earliest convenience.",
    fixInfo: "Have the vehicle scanned for diagnostic codes.",
  },
  {
    id: "overdrive-light",
    name: "Overdrive Light",
    description: "Indicates overdrive is off or there is a fault in the overdrive system.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Drive with caution. Fuel economy may be reduced.",
    fixInfo: "Turn overdrive on if needed. If flashing, have system checked.",
  },
  {
    id: "oil-change-reminder",
    name: "Oil Change Reminder",
    description: "It's time for an oil change based on mileage or time.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Schedule an oil change soon.",
    fixInfo: "Change oil and reset reminder.",
  },
  {
    id: "master-warning-light",
    name: "Master Warning Light",
    description: "A general warning for various systems. Check the display for more info.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Check the vehicle's info display for details.",
    fixInfo: "Address the specific warning shown in the display.",
  },
  {
    id: "icy-road-warning",
    name: "Icy Road Warning Light",
    description: "Road conditions may be icy. Drive with caution.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Reduce speed and drive carefully.",
    fixInfo: "Be alert for slippery conditions.",
  },
  {
    id: "gas-cap",
    name: "Gas/Fuel Cap",
    description: "The fuel cap is loose or missing, which can cause emissions issues.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Tighten or replace the fuel cap.",
    fixInfo: "Check and secure the fuel cap. Replace if damaged.",
  },
  {
    id: "esp-fault",
    name: "ESP Fault/Traction Control Malfunction",
    description: "There is a fault in the Electronic Stability Program or traction control system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Drive with caution. Reduced stability in poor conditions.",
    fixInfo: "Have the ESP/traction system checked.",
  },
  {
    id: "distance-warning",
    name: "Distance Warning",
    description: "You are too close to the vehicle ahead. System may alert or brake automatically.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Increase following distance.",
    fixInfo: "Maintain a safe distance from other vehicles.",
  },
  {
    id: "clogged-air-filter",
    name: "Clogged Air Filter",
    description: "The engine air filter is clogged and needs replacement.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Replace air filter soon for optimal performance.",
    fixInfo: "Install a new air filter.",
  },
  {
    id: "catalytic-converter-warning",
    name: "Catalytic Converter Warning",
    description: "There is a problem with the catalytic converter or emissions system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Service soon to avoid emissions/fuel issues.",
    fixInfo: "Have emissions system checked by a mechanic.",
  },
  {
    id: "brake-fluid",
    name: "Brake Fluid",
    description: "Brake fluid level is low or there is a leak in the system.",
    severity: "critical",
    image: PLACEHOLDER,
    urgency: "Stop and check brake fluid. Do not drive if leaking.",
    fixInfo: "Add brake fluid and check for leaks. Service if needed.",
  },
  {
    id: "brake-pad-warning",
    name: "Brake Pad Warning",
    description: "Brake pads are worn and need replacement soon.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Replace brake pads soon to maintain safe braking.",
    fixInfo: "Have brake pads inspected and replaced.",
  },
  {
    id: "brake-lights-warning",
    name: "Brake Lights Warning",
    description: "One or more brake lights are not working.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Replace faulty bulbs for safety.",
    fixInfo: "Check and replace brake light bulbs.",
  },
  {
    id: "automatic-gearbox-warning",
    name: "Automatic Gearbox Warning",
    description: "There is a problem with the automatic transmission.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Service transmission soon. Shifting may be affected.",
    fixInfo: "Have the transmission checked by a professional.",
  },
  {
    id: "awd-indicator",
    name: "All Wheel Drive (AWD/4WD)",
    description: "AWD/4WD system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If flashing or fault, service system soon.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "4wd-lock-indicator",
    name: "4 Wheel Drive (4WD) LOCK Indicator Light",
    description: "4WD lock mode is engaged or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not intended, disengage lock. Service if fault.",
    fixInfo: "Switch off lock mode or have system checked.",
  },
  {
    id: "air-suspension",
    name: "Air Suspension",
    description: "There is a problem with the air suspension system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Ride quality may be affected. Service soon.",
    fixInfo: "Have the air suspension system inspected.",
  },
  {
    id: "lamp-out",
    name: "Lamp Out",
    description: "One or more exterior lights are not working.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Replace faulty bulbs for safety.",
    fixInfo: "Check and replace exterior light bulbs.",
  },
  {
    id: "exterior-light-fault",
    name: "Exterior Light Fault",
    description: "There is a fault in the exterior lighting system.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "Check lights and service if needed.",
    fixInfo: "Inspect and repair lighting system.",
  },
  {
    id: "auto-high-beam",
    name: "Auto High Beam",
    description: "Automatic high beam system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "headlight-range-control",
    name: "Headlight Range Control",
    description: "Headlight range adjustment system is active or faulty.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "adaptive-light-system",
    name: "Adaptive Light System",
    description: "Adaptive headlights are active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "side-light-indicator",
    name: "Side Light Indicator",
    description: "Side lights are active.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off if not needed.",
  },
  {
    id: "rear-fog-lights-on",
    name: "Rear Fog Lights Switched On",
    description: "Rear fog lights are active.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off if not needed.",
  },
  {
    id: "rain-light-sensor",
    name: "Rain and Light Sensor",
    description: "Automatic rain or light sensor is active or faulty.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check sensor or have system checked.",
  },
  {
    id: "windshield-defrost",
    name: "Windshield Defrost / Rear Window Defrost",
    description: "Defrost system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless not working.",
    fixInfo: "Check system if windows do not clear.",
  },
  {
    id: "key-not-in-vehicle",
    name: "Key Not in Vehicle",
    description: "The key fob is not detected inside the vehicle.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Do not drive without the key. Retrieve it.",
    fixInfo: "Bring the key fob into the vehicle.",
  },
  {
    id: "hood-open",
    name: "Hood/Bonnet Open",
    description: "The hood/bonnet is open or not latched.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Stop and close the hood securely.",
    fixInfo: "Check and latch the hood.",
  },
  {
    id: "hazard-lights-on",
    name: "Hazard Lights On",
    description: "Hazard warning lights are active.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off if not needed.",
  },
  {
    id: "door-ajar",
    name: "Door Ajar",
    description: "One or more doors are open or not latched.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Stop and close all doors securely.",
    fixInfo: "Check and latch all doors.",
  },
  {
    id: "recirculated-cabin-air",
    name: "Recirculated Cabin Air",
    description: "Cabin air is being recirculated.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off recirculation if fresh air is desired.",
  },
  {
    id: "rear-spoiler-warning",
    name: "Rear Spoiler Warning",
    description: "There is a problem with the rear spoiler system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Have the spoiler system checked soon.",
    fixInfo: "Service the rear spoiler system.",
  },
  {
    id: "park-assist-pilot",
    name: "Parking with Park Assist Pilot",
    description: "Park assist system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "lane-assist",
    name: "Lane Assist",
    description: "Lane assist system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "key-fob-battery-low",
    name: "Key Fob Battery Low",
    description: "The key fob battery is low and needs replacement soon.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Replace key fob battery soon to avoid lockout.",
    fixInfo: "Replace the key fob battery.",
  },
  {
    id: "ignition-switch-warning",
    name: "Ignition Switch Warning",
    description: "There is a problem with the ignition switch or system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Service ignition system soon.",
    fixInfo: "Have the ignition system checked.",
  },
  {
    id: "hill-descent-control",
    name: "Hill Descent Control",
    description: "Hill descent control system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "forward-collision-warning",
    name: "Forward Collision Warning",
    description: "System detects a possible collision ahead.",
    severity: "critical",
    image: PLACEHOLDER,
    urgency: "Brake or steer to avoid collision.",
    fixInfo: "Stay alert and maintain safe distance.",
  },
  {
    id: "eco-driving-indicator",
    name: "Eco Driving Indicator",
    description: "Eco mode is active for fuel-efficient driving.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off eco mode if not desired.",
  },
  {
    id: "cruise-control",
    name: "Cruise Control",
    description: "Cruise control system is active.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off cruise control if not needed.",
  },
  {
    id: "adaptive-cruise-control",
    name: "Adaptive Cruise Control",
    description: "Adaptive cruise control is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "convertible-roof-warning",
    name: "Convertible Roof Warning Light",
    description: "There is a problem with the convertible roof system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Service roof system soon.",
    fixInfo: "Have the convertible roof system checked.",
  },
  {
    id: "brake-hold-indicator",
    name: "Brake Hold Indicator Light",
    description: "Brake hold system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "blind-spot-indicator",
    name: "Blind Spot Indicator Light",
    description: "Blind spot monitoring system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "auto-windscreen-wiping",
    name: "Auto Windscreen Wiping",
    description: "Automatic wiper system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "automatic-emergency-braking",
    name: "Automatic Emergency Braking (AEB)",
    description: "AEB system is active or there is a fault.",
    severity: "critical",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "winter-mode",
    name: "Winter Mode",
    description: "Winter driving mode is active.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off winter mode if not needed.",
  },
  {
    id: "start-stop-warning",
    name: "Start/Stop Warning Light",
    description: "There is a problem with the automatic start/stop system.",
    severity: "warning",
    image: PLACEHOLDER,
    urgency: "Service start/stop system soon.",
    fixInfo: "Have the system checked by a professional.",
  },
  {
    id: "speed-limiter",
    name: "Speed Limiter",
    description: "Speed limiter system is active or there is a fault.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "If not working as expected, service system.",
    fixInfo: "Check owner's manual or have system checked.",
  },
  {
    id: "ev-mode",
    name: "EV Mode",
    description: "Electric vehicle mode is active.",
    severity: "info",
    image: PLACEHOLDER,
    urgency: "No action needed unless unintended.",
    fixInfo: "Turn off EV mode if not needed.",
  },
]; 